Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Models/HomeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EventAttendanceAdmin.Web.Models
{
    public class HomeViewModel
    {
        public List<Event> ActiveEvents { get; set; }

        public List<Event> UpcomingEvents { get; set; }
    }
}

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EventAttendanceAdmin.Web.DAL;
using EventAttendanceAdmin.Web.Models;

namespace EventAttendanceAdmin.Web.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private EventContext db = new EventContext();

        public ActionResult Print(int id)
        {
            var e = db.Events.FirstOrDefault(x => x.Id == id);
            return View(e);
        }

        public ActionResult Index()
        {
            return View(db.Events.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Location,Start,End,Pin")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Events.Add(@event);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(@event);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Location,Start,End,Pin")] Event @event)
        {
            if (ModelState.IsValid)
            {
                db.Entry(@event).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(@event);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Event @event = db.Events.Find(id);
            if (@event == null)
            {
                return HttpNotFound();
            }
            return View(@event);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Event @event = db.Events.Find(id);
            db.Events.Remove(@event);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Controllers/HomeController.cs
using EventAttendanceAdmin.Web.DAL;
using EventAttendanceAdmin.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EventAttendanceAdmin.Web.Controllers
{
    public class HomeController : Controller
    {
        private EventContext db = new EventContext();

        public ActionResult Index()
        {
            var activeEvents = db.Events.Take(5).ToList();
            var upcomingEvents = db.Events.Take(5).ToList();
            var model = new HomeViewModel { ActiveEvents = activeEvents, UpcomingEvents = upcomingEvents };

            return View(model);
        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Views/Home/CreateEvent.cshtml
@model EventAttendanceAdmin.Web.Models.Event

@{
    ViewBag.Title = "CreateEvent";
}

<h2>CreateEvent</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Views/Home/EditEvent.cshtml
@model EventAttendanceAdmin.Web.Models.Event

@{
    ViewBag.Title = "EditEvent";
}

<h2>EditEvent</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Event</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Start, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Start, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Start, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.End, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.End, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.End, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Views/Home/Index.cshtml
@model EventAttendanceAdmin.Web.Models.HomeViewModel

@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1><i class="fa fa-calendar-check-o large"></i>&nbsp;Event Attendance</h1>
    <p class="lead">Easily track campus event attendance using student mobile devices and QR codes.</p>
    <p><a href="@Url.Action("Create", "Event")" class="btn btn-primary btn-lg">Create an event &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-6">
        <h2>Active Events</h2>
        <table class="table">
            @foreach (var item in Model.ActiveEvents)
            {
                <tr onclick='window.location.href = "@Url.Action("Details", "Event", new { id = item.Id })"' class="clickable">
                    <td>
                        <strong>@Html.DisplayFor(modelItem => item.Name)</strong>
                        @if (!string.IsNullOrEmpty(item.Location))
                        {
                            <text>&#64;</text> @Html.DisplayFor(modelItem => item.Location)
                        }
                        <br />
                        @Html.DisplayFor(modelItem => item.Start) to @Html.DisplayFor(modelItem => item.End)
                    </td>
                </tr>
            }
        </table>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Event")">View all &raquo;</a></p>
    </div>
    <div class="col-md-6">
        <h2>Upcoming Events</h2>
        <table class="table">
            @foreach (var item in Model.ActiveEvents)
            {
                <tr onclick='window.location.href = "@Url.Action("Details", "Event", new { id = item.Id })"' class="clickable">
                    <td>
                        <strong>@Html.DisplayFor(modelItem => item.Name)</strong>
                        @if (!string.IsNullOrEmpty(item.Location))
                        {
                            <text>&#64;</text> @Html.DisplayFor(modelItem => item.Location)
                        }
                        <br />
                        @Html.DisplayFor(modelItem => item.Start) to @Html.DisplayFor(modelItem => item.End)
                    </td>
                </tr>
            }
        </table>
        <p><a class="btn btn-default" href="@Url.Action("Index", "Event")">View all &raquo;</a></p>
    </div>
</div>

Admin/EventAttendanceAdmin/EventAttendanceAdmin.Web/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
}
<script>
    function testPost() {
        var checkin = { eventid: "1", studentidentifier: "Test Student" };
        $.ajax({
            type: "POST",
            data: JSON.stringify(checkin),
            url: "/api/checkin",
            contentType: "application/json"
        }).done(function (data) {
            console.log(data);
        }).fail(function (error) {
            console.log(error);
        });
    }
</script>

<h2>Test Page</h2>
<p>Simple page for performing feature tests</p>
<button onclick="testPost()">Test WebAPI post</button>